### ISSUE TITLE
thread "main" panick

### ISSUE THREAD

**Issue by gpalm** [OpenGM8/GM8Emulator#15]
![image](https://user-images.githubusercontent.com/30534203/76639641-8839a880-655f-11ea-9149-126878b452bf.png)
![image](https://user-images.githubusercontent.com/30534203/76639687-9e476900-655f-11ea-943c-a119d5605974.png)
So i tried start 2 fangames through gm8emulator and console shows that error in game.rs file, but i don't see any error in code, i am confused.
Pretty sure i am doing something wrong, but i don't know where i can ask questions for gm8emu

**Comment by Adamcake** [comment]
The first issue is due to GML's diamond operator, this was already fixed a few days ago in f9f6a81c71fa0ee38cd7465793292158bbfc3236, so you can fix that by pulling the latest commits. I'm not sure about the second one - I would need a copy of the game so I can debug it.

Would you be interested in talking with us on Discord? If you'd like to join my server at https://adamcake.com/discord I'll add you to the gm8emu dev channel.

**Comment by gpalm** [comment]
Okay, thank you for answer, i will do it.
Game - https://www.mediafire.com/file/gvtgpmw5sac8e7j/I_wanna_be_the_Salt.exe/file

I don't think that i will be utility in dev channel due of absence language knowing, so if questions about gm8emu are approved i will be very glad to join
