### ISSUE TITLE
Move old GM8Emulator C++ repo from GitLab to GitHub

### ISSUE THREAD

**Issue by cher-nov** [OpenGM8/GM8Emulator#19]
https://gitlab.com/GM8Emulator/GM8Emulator

$subj
And then just archive it.
I can make this by myself and then just transfer ownership to you.

**Comment by Adamcake** [comment]
The old C++ repo was already moved to Github, but it's private to avoid any confusion with the newer Rust version. The C++ repo isn't in development anymore as it's very incomplete, has several major issues and would basically need a complete redesign in order to have any more functionality added. The Rust project is the only one we're continuing with and it's already far more advanced than the C++ predecessor.

With that said, I can add you to the private repo if you really want access to it?

**Comment by cher-nov** [comment]
Actually I don't need GitHub-specific access for myself since I can access GitLab copy if I want to. :)

> The old C++ repo was already moved to Github, but it's private to avoid any confusion with the newer Rust version. The C++ repo isn't in development anymore as it's very incomplete, has several major issues and would basically need a complete redesign in order to have any more functionality added.

That's why I've created this issue. Currently, what really makes things confusing, is the separate GitLab repo. If it were on GitHub, being renamed to somewhat like `old_GM8Emulator` and archived, it would be much better, I believe.

There's a special button in repository settings, created specially for such historic purposes, that makes repo archived and read-only. It even adds a banner at the top of the page, saying "this repository is archived". ;)

**Comment by Adamcake** [comment]
Fair enough. We've deleted the Gitlab one and I've made the C++ repo public here: https://github.com/Adamcake/Legacy-GM8Emulator

I've renamed it to Legacy-GM8Emulator and updated readme.md to direct people to the newer project. I'd rather leave it under my own Github account since it isn't actually a part of OpenGM8.
