### ISSUE TITLE
improper room transition

### ISSUE THREAD

**Issue by YouCanNotKnow** [OpenGM8/GM8Emulator#45]
in I Wanna Be Your Banana pudding, the portals are supposed to have a little room transition where the previous screen fades out and the next screen fades in, but running it on the emulator warps you immediately without any transition. i dont know anything in rust and very little in gm8 but if i had to guess it would be something related to the now obsolete transition functions, like `transition_kind` and such

**Comment by Adamcake** [comment]
I expect this is just a transition_kind effect. The emulator doesn't support these yet, there are a couple missing in the Celebrate 100 TAS too.  

These are going to be quite tricky to support. Mainly due to the fact that they completely lock up the engine in a specialized frame-loop, stopping it from running any events or doing anything else for the duration of the transition. I can't really imagine how we're going to be able to give TAS-level control during the transition frames. For certain effects we will also need the ability to draw both rooms at once, which currently wouldn't be possible.

**Comment by Adamcake** [comment]
Okay, good news - apparently Floogle has already been doing some work on this on the dynamic-graphics branch, so it's not as far-off as I thought.
